### PR TITLE
updated a lot of stuff

### PR DESCRIPTION
**Pull request by TacoTheDank**
updated a bunch of dependencies

updated gradles

fixed a LOT of English mistakes

made app movable to sd card because the app alone takes around 85 MB on internal storage

### CODE REVIEW

**Comment by TacoTheDank** [comment]
@mohaxspb

**Comment by mohaxspb** [comment]
@TacoTheDank hello! 

Thanks for PR, especially for translation! And sorry for so much time to answer - I was on holiday and doesnt have Internet)

Could you please resolve conflicts in PR, which caused by recent commits from me - I update a lot of dependencies... After that I'll check how it builds and compiles and merge it)

**Comment by TacoTheDank** [comment]
kk

**Comment by mohaxspb** [comment]
@TacoTheDank thanks! I fix some build and compile errors and merge it)

**Pull request merged**
